# Generated by Django 4.2.1 on 2023-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('idDeck', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDeck', models.CharField(max_length=30)),
                ('precioDeck', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('runUsuario', models.CharField(max_length=10)),
                ('primerNombre', models.CharField(max_length=20)),
                ('segundoNombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apPaterno', models.CharField(max_length=25)),
                ('apMaterno', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
