# Generated by Django 4.2.1 on 2023-06-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaffleDecks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='deck',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='nombreDeck',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
