# Generated by Django 4.2.1 on 2023-06-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WaffleDecks', '0002_remove_deck_imagen_url_deck_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='imagen',
            field=models.ImageField(upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundoNombre',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decks', models.ManyToManyField(to='WaffleDecks.deck')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WaffleDecks.usuario')),
            ],
        ),
    ]
