# Generated by Django 4.2.1 on 2023-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaffleDecks', '0003_usuario_password_usuario_username_alter_deck_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comuna',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
    ]
