# Generated by Django 4.2.1 on 2023-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WaffleDecks', '0004_usuario_comuna_usuario_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='segundoNombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
